In [1]:
import selenium
from selenium import webdriver as wb
import warnings
warnings.filterwarnings('ignore')
import time
from tqdm import tqdm
import pandas as pd

In [2]:
web= wb.Chrome(r"C:\Users\kakar\Downloads\DS Data sets\chromedriver.exe")  
url=web.get("https://www.squareyards.com/resale/search?gclid=EAIaIQobChMI3JDVlsy49wIVfplmAh32aQj-EAAYASAAEgLH_vD_BwE%2CEAIaIQobChMI3JDVlsy49wIVfplmAh32aQj-EAAYASAAEgLH_vD_BwE&source=4tNJD6ZNNsJ9WlZBM48ZpA%3D%3D0n&propertyTypeName=&cityId=6&bedrooms=2%20BHK%2C3%20BHK%2C4%20BHK&propertyType=1%2C12%2C2")

In [ ]:
while web.find_element_by_class_name("infinite-loader"): ### infinite scrole down code
    web.execute_script('window.scrollTo(0,document.body.scrollHeight);')
    time.sleep(3)

In [ ]:
clickobj=web.find_elements_by_class_name('tlWrp')### for all product

In [ ]:
len(clickobj)

In [ ]:
productinfo=web.find_elements_by_class_name('tlSrtlst')### for each and every product links

In [ ]:
productinfo[0].get_attribute('data-url')

In [ ]:
len(productinfo) ## total links of products

In [ ]:
productinfo[0]

In [ ]:
web.find_elements_by_class_name('tlSrtlst')[1].get_attribute('data-url') ## Details and product information links description

In [ ]:
urls=[]
for i in range(len(productinfo)):  ## loop to collect all product detalils information (at a time) 
    urls.append(productinfo[i].get_attribute('data-url'))

In [ ]:
len(urls)

In [ ]:
urls

In [ ]:
all_links=pd.DataFrame(urls)

In [ ]:
all_links.columns=['urls']

In [ ]:
all_links.to_csv(r"C:\Users\kakar\Downloads\DS Data sets\realestate_data1.csv",index=False)

In [ ]:
web.find_elements_by_class_name('projectInfoBoxLi')[0].text   ## for each product deatils and decription

In [ ]:
web.find_element_by_class_name('projectPriceBox').text

## START

In [3]:
links=pd.read_csv(r'C:\Users\kakar\Downloads\DS Data sets\realestate_data1.csv')
links.head()

                                                urls
0  https://www.squareyards.com/resale-3-bhk-pooja...
1  https://www.squareyards.com/resale-3-bhk-pooja...
2  https://www.squareyards.com/resale-3-bhk-300-s...
3  https://www.squareyards.com/resale-3-bhk-pooja...
4  https://www.squareyards.com/resale-3-bhk-pooja...

In [4]:
web= wb.Chrome(r"C:\Users\kakar\Downloads\DS Data sets\chromedriver.exe")
from tqdm import tqdm
all_products=[]
for link in tqdm(links['urls']):
    product=[]
    try:
        web.get(link)
        product.append(link)  # link
        product.append(web.find_element_by_class_name('projectPriceBox').text) # price
        columns=['Last Updated','Listing Type','Property Type','Building Type','City','Locality',
                 'Area','Price','Possession Status','Furnishing Status','Number of Rooms',
                 'Number of Bathroom','Number of Parking','View /Facing','Floor No.','Tower/Block',
                 'Additional Rooms','Age of Property (Years)','Unit No','Total Floor Count']
        for j in columns:
            value=[]
            for i in range(0,len(web.find_elements_by_class_name('projectInfoBoxLi'))):
                if (web.find_elements_by_class_name('projectInfoBoxLi')[i].text.split('\n')[0])==j:
                    value.append(web.find_elements_by_class_name('projectInfoBoxLi')[i].text.split('\n')[1])
            if len(value) > 0:
                product.append(value[0])
            else:
                product.append(np.NaN)
        all_products.append(product)
        
    except:
        pass

columns.insert(0,'links')
columns.insert(1,'price')

100%|██████████| 4315/4315 [11:48:17<00:00,  9.85s/it]

In [5]:
df=pd.DataFrame(all_products,columns=columns)
df

,links,price,Last Updated,Listing Type,Property Type,Building Type,City,Locality,Area,Price,...,Number of Rooms,Number of Bathroom,Number of Parking,View /Facing,Floor No.,Tower/Block,Additional Rooms,Age of Property (Years),Unit No,Total Floor Count
0,https://www.squareyards.com/resale-3-bhk-pooja...,₹ 1.04 Cr.,20 Apr 2022,Sale,Residential,Apartment,Hyderabad,Miyapur,1680 Sq.Ft. (Built-up Area),1.04 Cr.,...,3,2,2,North,2,1,"Pooja Room,Study Room,Extra Room",0-1,1,5
1,https://www.squareyards.com/resale-3-bhk-pooja...,₹ 1.04 Cr.,03 May 2022,Sale,Residential,Apartment,Hyderabad,Kondapur,1600 Sq.Ft. (Built-up Area),1.04 Cr.,...,3,3,1,West,2,1,"Pooja Room,Study Room",0-1,202,5
2,https://www.squareyards.com/resale-3-bhk-pooja...,₹ 69.46 Lac,28 Apr 2022,Sale,Residential,Apartment,Hyderabad,Kollur,1579 Sq.Ft. (Built-up Area),69.46 Lac,...,3,3,2,East,7,3,Pooja Room,0-1,95,15
3,https://www.squareyards.com/resale-3-bhk-pooja...,₹ 1.13 Cr.,29 Apr 2022,Sale,Residential,Apartment,Hyderabad,Kondapur,1515 Sq.Ft. (Built-up Area),1.13 Cr.,...,3,2,1,East,5,1,Pooja Room,0-1,10,5
4,https://www.squareyards.com/resale-2-bhk-serva...,₹ 46 Lac,29 Apr 2022,Sale,Residential,Apartment,Hyderabad,Tolichowki,1100 Sq.Ft. (Built-up Area),46 Lac,...,2,2,1,East,2,A,Servant Room,0-1,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1975,https://www.squareyards.com/resale-2-bhk-pooja...,₹ 63.25 Lac,14 Jul 2021,Sale,Residential,Apartment,Hyderabad,Bachupally,1150 Sq.Ft. (Built-up Area),63.25 Lac,...,2,2,1,East,6,A,Pooja Room,0-1,601,22
1976,https://www.squareyards.com/resale-2-bhk-pooja...,₹ 26.62 Lac,09 Nov 2021,Sale,Residential,Apartment,Hyderabad,Isnapur,1110 Sq.Ft. (Built-up Area),26.62 Lac,...,2,2,2,South,2,2,"Pooja Room,Study Room",0-1,25,4
1977,https://www.squareyards.com/resale-3-bhk-extra...,₹ 36.32 Lac,02 Dec 2021,Sale,Residential,Apartment,Hyderabad,Bandlaguda,1130 Sq.Ft. (Built-up Area),36.32 Lac,...,3,2,1,North,6,27,Extra Room,0-1,2,5
1978,https://www.squareyards.com/resale-2-bhk-pooja...,₹ 71.06 Lac,08 Dec 2021,Sale,Residential,Apartment,Hyderabad,Pragathi Nagar,1292 Sq.Ft. (Built-up Area),71.06 Lac,...,2,2,2,East,1,2,Pooja Room,0-1,2,7
1979,https://www.squareyards.com/resale-2-bhk-pooja...,₹ 55 Lac,07 Dec 2021,Sale,Residential,Apartment,Hyderabad,Suraram Colony,1250 Sq.Ft. (Built-up Area),55 Lac,...,2,2,1,East,2,a,"Pooja Room,Study Room,Extra Room",0-1,220,10

In [6]:
df.head()

,links,price,Last Updated,Listing Type,Property Type,Building Type,City,Locality,Area,Price,...,Number of Rooms,Number of Bathroom,Number of Parking,View /Facing,Floor No.,Tower/Block,Additional Rooms,Age of Property (Years),Unit No,Total Floor Count
0,https://www.squareyards.com/resale-3-bhk-pooja...,₹ 1.04 Cr.,20 Apr 2022,Sale,Residential,Apartment,Hyderabad,Miyapur,1680 Sq.Ft. (Built-up Area),1.04 Cr.,...,3,2,2,North,2,1,"Pooja Room,Study Room,Extra Room",0-1,1,5
1,https://www.squareyards.com/resale-3-bhk-pooja...,₹ 1.04 Cr.,03 May 2022,Sale,Residential,Apartment,Hyderabad,Kondapur,1600 Sq.Ft. (Built-up Area),1.04 Cr.,...,3,3,1,West,2,1,"Pooja Room,Study Room",0-1,202,5
2,https://www.squareyards.com/resale-3-bhk-pooja...,₹ 69.46 Lac,28 Apr 2022,Sale,Residential,Apartment,Hyderabad,Kollur,1579 Sq.Ft. (Built-up Area),69.46 Lac,...,3,3,2,East,7,3,Pooja Room,0-1,95,15
3,https://www.squareyards.com/resale-3-bhk-pooja...,₹ 1.13 Cr.,29 Apr 2022,Sale,Residential,Apartment,Hyderabad,Kondapur,1515 Sq.Ft. (Built-up Area),1.13 Cr.,...,3,2,1,East,5,1,Pooja Room,0-1,10,5
4,https://www.squareyards.com/resale-2-bhk-serva...,₹ 46 Lac,29 Apr 2022,Sale,Residential,Apartment,Hyderabad,Tolichowki,1100 Sq.Ft. (Built-up Area),46 Lac,...,2,2,1,East,2,A,Servant Room,0-1,5,5

In [7]:
df.to_csv(r'C:\Users\kakar\Downloads\DS Data sets\Realestate_final.csv',index= False)

In [9]:
df.iloc()